title: joomla-twig
description: A starter kit for using Tailwind with Jekyll
show_nav: true
show_sidebar: true
show_downloads: true

exclude:
  - package.json
  - node_modules
  - gulpfile.js
  - package-lock.json
  - Gemfile
  - Gemfile.lock
